services:
  # A Docker web service
  - type: web
    name: flowai
    runtime: docker
    dockerfilePath: ./docker/render.Dockerfile
    repo: https://github.com/digitranslab/flowai
    branch: main
    plan: standard
    healthCheckPath: /health_check
    autoDeploy: false
    envVars:
      - key: FLOWAI_DATABASE_URL
        value: sqlite:////app/data/.cache/digitranslab/flowai.db
      - key: FLOWAI_HOST
        value: 0.0.0.0
      - key: FLOWAI_PORT
        # default render port https://docs.render.com/web-services#port-binding
        value: 10000
      - key: FLOWAI_LOG_LEVEL
        value: INFO
    disk:
      name: flowai-data
      mountPath: /app/data
