services:
  # A Docker web service
  - type: web
    name: minerva
    runtime: docker
    dockerfilePath: ./docker/render.Dockerfile
    repo: https://github.com/digitranslab/minerva
    branch: main
    plan: standard
    healthCheckPath: /health_check
    autoDeploy: false
    envVars:
      - key: MINERVA_DATABASE_URL
        value: sqlite:////app/data/.cache/digitranslab/minerva.db
      - key: MINERVA_HOST
        value: 0.0.0.0
      - key: MINERVA_PORT
        # default render port https://docs.render.com/web-services#port-binding
        value: 10000
      - key: MINERVA_LOG_LEVEL
        value: INFO
    disk:
      name: minerva-data
      mountPath: /app/data
