services:
  minerva:
    image: digitranslab/minerva:1.1.8.dev0 # or another version tag on https://hub.docker.com/r/digitranslab/minerva
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - MINERVA_DATABASE_URL=postgresql://minerva:minerva@postgres:5432/minerva
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - MINERVA_CONFIG_DIR=app/minerva
    volumes:
      - minerva-data:/app/minerva

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: minerva
      POSTGRES_PASSWORD: minerva
      POSTGRES_DB: minerva
    ports:
      - "5432:5432"
    volumes:
      - minerva-postgres:/var/lib/postgresql/data

volumes:
  minerva-postgres:
  minerva-data:
