version: "3.8"

services:
  flowai:
    image: digitranslab/flowai:1.0-alpha
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - FLOWAI_DATABASE_URL=postgresql://flowai:flowai@postgres:5432/flowai
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - FLOWAI_CONFIG_DIR=app/flowai
    volumes:
      - flowai-data:/app/flowai

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: flowai
      POSTGRES_PASSWORD: flowai
      POSTGRES_DB: flowai
    ports:
      - "5432:5432"
    volumes:
      - flowai-postgres:/var/lib/postgresql/data

volumes:
  flowai-postgres:
  flowai-data:
