networks:
  dev-minerva:

services:
  minerva:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    image: dev-minerva
    container_name: dev-minerva
    restart: always
    ports:
      - "7860:7860"
      - "3000:3000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - MINERVA_DATABASE_URL=postgresql://minerva:minerva@postgres:5432/minerva
      - MINERVA_SUPERUSER=minerva
      - MINERVA_SUPERUSER_PASSWORD=minerva
      - MINERVA_CONFIG_DIR=/var/lib/minerva
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      - postgres
    networks:
      -  dev-minerva


  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: minerva
      POSTGRES_PASSWORD: minerva
      POSTGRES_DB: minerva
    ports:
      - "5432:5432"
    networks:
      -  dev-minerva

