networks:
  dev-flowai:

services:
  flowai:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    image: dev-flowai
    container_name: dev-flowai
    restart: always
    ports:
      - "7860:7860"
      - "3000:3000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - FLOWAI_DATABASE_URL=postgresql://flowai:flowai@postgres:5432/flowai
      - FLOWAI_SUPERUSER=flowai
      - FLOWAI_SUPERUSER_PASSWORD=flowai
      - FLOWAI_CONFIG_DIR=/var/lib/flowai
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      - postgres
    networks:
      -  dev-flowai


  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: flowai
      POSTGRES_PASSWORD: flowai
      POSTGRES_DB: flowai
    ports:
      - "5432:5432"
    networks:
      -  dev-flowai

